---
- hosts: 172.31.13.213
  become: yes
  tasks:
  - name: Download Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: yes
  - name: Configure Docker Repository
    apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
      state: present
    become: yes
  - name: Installing Docker
    apt:
      name: docker-ce
      state: latest
      update-cache: true