---
- hosts: all
  become: yes
  tasks: 
  - name: Installing java
    apt:
      name: openjdk-11-jdk
      state: present
  - name: Installing Maven
    apt:
      name: maven
      state: present
  - name: Download Jenkins
    apt_key: 
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present
    become: yes
  - name: Configure Jenkins Repository
    apt_repository:
      repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
      state: present
    become: yes
  - name: Installing Jenkins
    apt:
      name: jenkins
      state: latest
      update-cache: yes
  - name: Start Jenkins
    systemd:
      name: jenkins
      state: started