---
- hosts: 172.31.3.28
  become: yes
  tasks:
  - name: Insttalling java
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Add JFrog repository
    yum_repository:
      name: jfrog-artifactory-oss-rpms
      description: JFrog Artifactory OSS RPMS
      baseurl: https://jfrog.bintray.com/artifactory-rpms
      gpgcheck: yes
      gpgkey: https://bintray.com/user/downloadSubjectPublicKey?username=jfrog
      enabled: yes
      exclude: ''
    register: jfrog_repo
  - name: Install JFrog Artifactory
    yum:
      name: frog-artifactory-oss-rpms
      state: present
  - name: Start JFrog
    service:
      name: artifactory
      state: started