---
- hosts: 172.31.3.28
  become: yes
  tasks:
  - name: Insttalling java
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Install JFrog
    yum:
      name: jfrog-artifactory-oss
      state: present

  - name: Configure JFrog
    template:
      src: jfrog.config
      dest: /opt/jfrog/artifactory/etc/artifactory.system.properties
      owner: artifactory
      group: artifactory
      mode: '0644'

  - name: Start JFrog
    systemd:
      name: artifactory
      state: started
      enabled: yes