---
- hosts: 172.31.3.28
  become: yes
  vars:
    jfrog_version: "7.28.4"
  tasks:
  - name: Insttalling java
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Download JFrog Artifactory
    get_url:
      url: "https://bintray.com/jfrog/artifactory-rpms/rpm/{{ artifactory_version }}/el7/x86_64/jfrog-artifactory-{{ artifactory_version }}-1.el7.noarch.rpm"
      dest: "/tmp/jfrog-artifactory.rpm"
  - name: Install JFrog Artifactory
    yum:
      name: "/tmp/jfrog-artifactory.rpm"
      state: present
  - name: Start JFrog
    service:
      name: artifactory
      state: started
